### ISSUE TITLE
no read_rpt in rl_wq folder

### ISSUE THREAD

**Issue by JimengShi** [UVAdMIST/swmm_wq_rl#1]
Dear Sir or Madam,

Greeeeat work! 

Could I ask you to have a look at the 25th and 26th rows of the file "/rl_wq/hague_ddpg_tune"? There is no read_rpt and swmm_utilis in the repository?

`from swmm_rl_hague.read_rpt import get_ele_df, get_file_contents, get_summary_df, get_total_flooding, get_mass_reacted`
`from swmm_rl_hague.swmm_utils import get_result_df`

Please let me know if you put it in another folder or something else. Thanks!

**Comment by bdb3m** [comment]
Hello @JimengShi. Thanks for your interest and question! 

The swmm_utils file is here: https://github.com/UVAdMIST/swmm_wq_rl/blob/main/processing/swmm_utils.py. You will find the functions from the read_report script in the swmm_utils file as well.

Hope that helps!

**Comment by JimengShi** [comment]
Thanks so much, @bdb3m.  It makes sense.

**Comment by bdb3m** [comment]
Great!
